services:
  db:
    container_name: WordPress_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: MYSQL_DB
      MYSQL_USER: grodriguez
      MYSQL_PASSWORD: su
      MYSQL_ROOT_PASSWORD: su
    volumes:
      - ./db-data:/var/lib/mysql

  wordpress:
    container_name: wp_wordpress
    image: wordpress:php8.2-apache
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: MYSQL_DB
      WORDPRESS_DB_USER: grodriguez
      WORDPRESS_DB_PASSWORD: su
    volumes:
      - ./wp-data:/var/www/html

  phpmyadmin:
    container_name: WordPress_phpmyadmin
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
      